server:
  port: 8081

spring:
  application:
    name: flight-schedule-server

  ai:
    mcp:
      server:
        enabled: true
        name: mcp-flight-schedule-server
        version: 1.0.0
        type: SYNC
        sse-message-endpoint: /mcp/flight/messages

  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

logging:
  level:
    org.springframework.ai: TRACE
    org.springframework.web: TRACE
    org.hibernate.SQL: debug
    org.hibernate.type: trace

