server:
  port: 8080

spring:
  application:
    name: mcp-homework-server

  ai:
    openai:
      api-key: '${OPENAI_API_KEY}'
      base-url: '${OPENAI_API_URL}'

    mcp:
      server:
        enabled: true
        name: mcp-homework-server
        version: 1.0.0
        type: SYNC
        sse-mssage-endpoint: /mcp/message

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update  # create, update, validate, none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
