server:
  port: 8080

spring:
  application:
    name: mcp-homework-server

  ai:

    mcp:
      server:
        enabled: true
        name: mcp-homework-server
        version: 1.0.0
        type: ASYNC
        sse-message-endpoint: /mcp/messages

  r2dbc:
    url: r2dbc:h2:mem:///testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    pool:
      enabled: true
      initial-size: 5
      max-size: 10
      max-idle-time: 30m

    h2:
      console:
        enabled: true
        path: /h2-console
    sql:
      init:
        mode: always
        platform: h2
        encoding: UTF-8
        schema: classpath:schema.sql
        data: classpath:data.sql

logging:
  level:
    org.springframework.ai: TRACE
    org.springframework.web: TRACE
    org.springframework.web.reactive: TRACE
    org.springframework.r2dbc: DEBUG
    io.r2dbc: DEBUG
