server:
  port: 8080

spring:
  application:
    name: api-homework

  datasource:
    # H2 DB ??: http://localhost:8080/h2-console
    url: jdbc:h2:mem:testdb # DB ?? -> ???
#    url: jdbc:h2:mem:testdb;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE # DB ?? -> ???
#    url: jdbc:h2:file:~/mydb # DB ?? -> File
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update  # create, update, validate, none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
